### ISSUE TITLE
Improve description in the Moodle Plugins directory

### ISSUE THREAD

**Issue by mudrd8mz** [Pedagotheque/moodle-local_regperiod#1]
Both short description and long description fields at https://moodle.org/plugins/local_regperiod are identical which is useless:

![image](https://user-images.githubusercontent.com/85831/134901119-efb42e2d-9f51-4549-a21f-2e0985589540.png)

Please use the short description to shortly describe the essential functionality (such as "The plugin allows to define a period during which the user is allowed to log in and use the site." or so) and then have all the details well formatted in the long description field only.

**Comment by martin-call-learning** [comment]
The short description is now different from the complete one.
